### ISSUE TITLE
LoggerMessage.Define requires all parameters are defined in the formatString.

### ISSUE THREAD

**Issue by stevejgordon** [aspnet/Logging#840] opened 2018-05-30 14:57 UTC
I'm currently moving some logging over to the more performant approach of adding extensions to Actions created using LoggerMessage.Define. In some cases, our current logging is passing extra params which are not used in the log message but are recorded as structured objects using Serilog.

It doesn't appear that currently, I can define anything which doesn't include placeholders for all of the objects in the formatString. Doing so results in an ArgumentException.

> System.ArgumentException: 'The format string 'xxx' does not have the expected number of named parameters. Expected 2 parameter(s) but found 1 parameter(s).'

Is there any possibility of extending this to support cases where not all of the objects are expected to be rendered into the formatted message?

**Comment by muratg** [comment] 2018-06-29 21:35
@stevejgordon Any recommendations on how to achieve this?

**Comment by stevejgordon** [comment] 2018-07-01 07:45
@muratg I haven't dug into the codebase to know what's possible but I'm wondering if there could be an overload that takes a Dictionary<string, object> of additional data which is then included in the serialised log messages? Similar to what seems to be possible when using scopes?

**Comment by agehrke** [comment] 2018-07-13 08:37
Yes, I have been wondering about the same thing myself. The action returned from `LoggerMessage.Define()` will log a `TState` type of some internal type `LogValues<T0, T1, ... TN>` which encapsulates the arguments passed to action from Define(). The given `LogValues` type is optimized for the N number of arguments.

Example:
```csharp
public static Action<ILogger, T1, T2, Exception> Define<T1, T2>(LogLevel logLevel, EventId eventId, string formatString)
{
    var formatter = CreateLogValuesFormatter(formatString, expectedNamedParameterCount: 2);

    return (logger, arg1, arg2, exception) =>
    {
        if (logger.IsEnabled(logLevel))
        {
            logger.Log(logLevel, eventId, new LogValues<T1, T2>(formatter, arg1, arg2), exception, LogValues<T1, T2>.Callback);
        }
    };
}
```

The usage of `TState`  in `ILogger.Log<TState>()` method is implementation specific:

* Most loggers only uses the state to format message string by passing it to `Func<TState, Exception, string> formatter` 
* [NLog tries to cast the `TState` object into a `IReadOnlyList<KeyValuePair<string, object>>`](https://github.com/NLog/NLog.Extensions.Logging/blob/master/src/NLog.Extensions.Logging/Logging/NLogLogger.cs#L40) and if successful adds state to it's LogEventInfo class.

**Comment by muratg** [comment] 2018-10-18 21:59
Thank you for your feedback. We're closing this issue as the behavior discussed seems to be by design.

**Closed by muratg** 2018-10-18 21:59 UTC
