### ISSUE TITLE
Exception in Logger.IsEnabled does not always throw

### ISSUE THREAD

**Issue by josephgardner** [aspnet/Logging#443] opened 2016-05-31 21:58 UTC
PR #224 aggregates exceptions in both `IsEnabled` and `Log` to prevent an exception in one logger from stopping execution of another logger. 

However, `IsEnabled` will only throw if an exception occurs and all other loggers return false. Exceptions are swallowed if any logger returns true. 

This is because `IsEnabled` returns immediately if any logger returns true (even if previous loggers threw exceptions, or subsequent loggers would have thrown.)

https://github.com/aspnet/Logging/blob/d05bbde7f18f98a2ab05796b2f1b3d7afc105f17/src/Microsoft.Extensions.Logging/Logger.cs#L79

Is this by design?

**Comment by jblazek** [comment] 2016-06-01 14:11
The test IsEnabled_IgnoresExceptionInIntermediateLoggers in LoggerTest that is related to this functionality is 'Acting' on the Log method, not the IsEnabled method.

Because of this, the test doesn't really help make it clear what the intended behavior is.

**Comment by muratg** [comment] 2018-11-05 23:30
Closing this as we're preparing to move this repo over to Extensions.

**Closed by muratg** 2018-11-05 23:30 UTC
