### ISSUE TITLE
Expected ordering log message with indexes

### ISSUE THREAD

**Issue by 304NotModified** [aspnet/Logging#462] opened 2016-07-13 21:28 UTC
What is the expected result of:

``` c#
Logger.LogTrace("zero: {0} two: {2} one: {1}", "0", "1", "2");
```

A) `zero: 0  two: 2 one:1`
or
B) `zero: 0  two: 1 one:2`

B is currently the result of the passed formatter. 

In Serilog there is the rule:

> Formats that use numeric property names, like {0} and {1} exclusively, will be matched with the log method's parameters by treating the property names as indexes; this is identical to string.Format()'s behaviour

and so that would result in A and also with the experience with `string.format`, I would expect A.

This is an issue with the NLog Extension, but it is using the `formatter` passed to `ILogger.Log<TState>`

**Comment by cesarbs** [comment] 2016-07-13 21:56
@kichalla

**Comment by 304NotModified** [comment] 2016-07-20 18:23
Please respond on this.

**Comment by kichalla** [comment] 2016-07-20 18:37
cc @muratg @Eilon @rynowak  This feels like a valid thing to do

**Comment by Eilon** [comment] 2016-07-20 19:37
I'm quite sure we didn't try to implement ordering based on interpreting the key values as integers... I was not aware of SeriLog's ordering behavior in this case.

I think it's a breaking change to do this though...

**Comment by 304NotModified** [comment] 2016-07-21 04:43
Yes it would be a breaking change. Consistent with string.Format is nice as the syntax looks the same. 

Any way, if this is by design,  please document it :)

**Comment by muratg** [comment] 2016-07-26 16:13
@danroth27 Could you get the right folks to document this behavior?

**Comment by 304NotModified** [comment] 2016-07-26 17:15
So it's by design? Good to know, so we can close also the bug report at our site

**Comment by Eilon** [comment] 2016-07-26 17:22
It is certainly by design at this time. The keys are always opaque, so even if they happen to "look like" numbers, they're still opaque strings.

**Comment by 304NotModified** [comment] 2016-07-26 17:23
OK thanks for the feedback! :+1:

**Comment by thirdwaffle** [comment] 2016-07-26 22:45
@muratg It looks like this is already documented on [docs.asp.net](https://docs.asp.net/en/latest/fundamentals/logging.html#implementing-logging-in-your-application). It took me a while to find it on that page, and it doesn't go in to much detail. I'd say it definitely needs its own section.

> The call to the log method can utilize a format string with named placeholders (like {path}). These placeholders are populated in the order in which they appear by the args values passed into the method call.

+1 for adding some more documentation explaining the behaviour when numbers are used instead of names. Especially when other examples of logging on that same page use numbered parameters.

**Comment by muratg** [comment] 2017-05-12 20:56
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.

**Closed by muratg** 2017-05-12 20:56 UTC
