### ISSUE TITLE
EventLog logger for K

### ISSUE THREAD

**Issue by glennc** [aspnet/Logging#6] opened 2014-03-03 23:35 UTC
Create a new package for an EventLog sink and expose the API that the user would put in their startup class: `app.UseEventLog();`

Figure out how to register the category name that requires elevated privilege. P/Invoke for accessing event log.

**Comment by davidfowl** [comment] 2015-03-05 11:50
Dupe of #83

**Closed by davidfowl** 2015-03-05 11:50 UTC
