### ISSUE TITLE
Avoid a dedicated thread in ConsoleLoggerProcessor

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/Logging#560] opened 2017-02-17 17:15 UTC
https://github.com/aspnet/Logging/blob/db73396309d4989925486061e0a88997b966ae0a/src/Microsoft.Extensions.Logging.Console/Internal/ConsoleLoggerProcessor.cs#L22

**Comment by muratg** [comment] 2017-06-14 23:17
The issue is we're using an additional thread which stays idle for the most of the time. Backlogging for now to see if this causes any real issues.

**Comment by malachib** [comment] 2018-04-03 17:30
There's an additional impetus to this in that newly-solidifying Blazor doesn't support threading (evidently a WASM limitation) but would be nice to use this console logger in that scenario

**Comment by muratg** [comment] 2018-04-04 02:38
Interesting point @malachib.  

cc @danroth27 and @SteveSandersonMS for their thoughts on that. Also, do we have a work item tracking the single-thread limitations for Blazor somewhere?

**Comment by danroth27** [comment] 2018-04-04 03:35
WebAssembly is inherently single threaded, so there really isn't anything we can do about that in Blazor. 

Not sure if we have any plans to use Microsoft.Extensions.Logging in Blazor. @SteveSandersonMS ?

**Comment by SteveSandersonMS** [comment] 2018-04-04 11:07
I'm not sure there's really any problem (for Blazor) here. Although WebAssembly is single-threaded, we still support `Task` and asynchrony. Only one task runs at any given instant, but they still do run, just like JavaScript asynchrony.

For example, the following code is fine in Blazor:

```
Task.Factory.StartNew(async () =>
{
    Console.WriteLine("Hello");
    await Task.Delay(3000);
    Console.WriteLine("Goodbye");
});
```

So I'm not aware that we have any special requirements for logging. We may well want to use Microsoft.Extensions.Logging, but it's not something we're urgently making a plan about right now. The thing you *can't* do is `new Thread`, but it doesn't look like ConsoleLoggerProcessor needs to do that anyway.

**Comment by malachib** [comment] 2018-04-05 19:14
@SteveSandersonMS right on.  I tried it out a few days ago (Blazor 0.1.0) and was met with threading issues, but that could just be the newness of it all.

**Comment by campersau** [comment] 2018-04-29 09:04
So it looks like https://github.com/aspnet/Logging/pull/739 broke `WebAssembly` compatibility by using `Thread`s.
https://github.com/aspnet/Logging/blob/d09254b564c9f108a136287f558fd272100b84b1/src/Microsoft.Extensions.Logging.Console/Internal/ConsoleLoggerProcessor.cs#L22-L27

**Comment by pakrym** [comment] 2018-11-16 16:40
Closing this. We can write a separate logger implementation for blazor if requirement comes up.

I think using `Console.WriteLine` in the browser is very limiting anyway considering how rich browser console is.

**Closed by pakrym** 2018-11-16 16:40 UTC
