### ISSUE TITLE
EventLogLogger may throw an exception when the message is too big

### ISSUE THREAD

**Issue by Mertsch** [aspnet/Logging#305] opened 2015-11-26 22:29 UTC
The Event log has a message size restriction
```Log entry string is too long. A string written to the event log cannot exceed 32766 characters.```

Note: The limit is not 32766 characters, but 31839!

Why 31839? See here http://msdn.microsoft.com/en-us/library/windows/desktop/aa363679.aspx
Also look at .NET framework code, which limits to 32766 see System.Diagnostics.EventLog.InternalWriteEvent

```
Microsoft.Data.Entity.DbContext
An exception occurred in the database while saving changes.
Microsoft.Data.Entity.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.AggregateException: An error occurred while writing to logger(s). ---> System.ArgumentException: Log entry string is too long. A string written to the event log cannot exceed 32766 characters.
   at System.Diagnostics.EventLogInternal.InternalWriteEvent(UInt32 eventID, UInt16 category, EventLogEntryType type, String[] strings, Byte[] rawData, String currentMachineName)
   at System.Diagnostics.EventLogInternal.WriteEntry(String message, EventLogEntryType type, Int32 eventID, Int16 category, Byte[] rawData)
   at System.Diagnostics.EventLog.WriteEntry(String message, EventLogEntryType type, Int32 eventID, Int16 category)
   at Microsoft.Extensions.Logging.EventLog.EventLogLogger.Log(LogLevel logLevel, Int32 eventId, Object state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.Log(LogLevel logLevel, Int32 eventId, Object state, Exception exception, Func`3 formatter)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.Log(LogLevel logLevel, Int32 eventId, Object state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log(LogLevel logLevel, Int32 eventId, Object state, Exception exception, Func`3 formatter)
   at Microsoft.Data.Entity.Infrastructure.SensitiveDataLogger`1.Microsoft.Extensions.Logging.ILogger.Log(LogLevel logLevel, Int32 eventId, Object state, Exception exception, Func`3 formatter)
   at Microsoft.Data.Entity.Storage.RelationalLoggerExtensions.LogInformation[TState](ILogger logger, RelationalLoggingEventId eventId, Func`1 state, Func`2 formatter)
   at Microsoft.Data.Entity.Storage.RelationalLoggerExtensions.LogCommandExecuted(ISensitiveDataLogger logger, DbCommand command, Nullable`1 elapsedMilliseconds)
   at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.<ExecuteAsync>d__20`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.<ExecuteReaderAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Data.Entity.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__28.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Data.Entity.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Data.Entity.Update.Internal.BatchExecutor.<ExecuteAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Data.Entity.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Data.Entity.DbContext.<SaveChangesAsync>d__28.MoveNext()
```

**Comment by Mertsch** [comment] 2015-12-10 10:10
I can send a pull request that mitigates the issue by trimming the message to a maximum number of characters.
But I have one question. What would you think would be preferable?
```<much more chars> this is too long```
Trim to
```<much more chars> this is to```
or
```<much more chars> this is...```

**Comment by muratg** [comment] 2015-12-10 16:54
I think this is by design. I think we rather throw and get the attention of the developer instead of silently trimming the messages and losing data.

**Comment by Eilon** [comment] 2015-12-10 18:03
@muratg interesting. How evil would it be if we split the log entry and logged each section? I know it's super evil. But it seems worse to randomly crash the app...

**Comment by muratg** [comment] 2015-12-10 18:20
@Eilon I think it would be OK if we make it optional. Perhaps with a new boolean property on https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.EventLog/EventLogSettings.cs

**Comment by Eilon** [comment] 2015-12-10 22:03
Or just always do it and beg forgiveness later?

**Comment by muratg** [comment] 2015-12-10 23:36
:ok:

**Comment by muratg** [comment] 2015-12-18 18:42
Per @Eilon's suggestion we've decided to split the messages if they're larger than the limit.  Assigning to @kichalla

**Comment by kichalla** [comment] 2015-12-30 19:23
6c29db36515ccd86dc367b5b07d790c2ff7a898b

**Closed by kichalla** 2015-12-30 19:23 UTC
Labels: 3 - Done, bug
