### ISSUE TITLE
Logger.Log...()  overloads throw when args is compile-time type Object and runtime value null

### ISSUE THREAD

**Issue by chrisfcarroll** [aspnet/Logging#767] opened 2018-03-01 20:28 UTC
```
using Microsoft.Extensions.Logging; // 2.0.0.0 from NuGet

[Test]
public void MsLoggerShouldNotThrowGivenASingleNullParameter()
{
	var logger = new LoggerFactory().AddConsole().CreateLogger("");
	logger.LogWarning("Log this:{0}", null, null);
	logger.LogWarning("Log this:{0}", null as string);
	logger.LogWarning("Log this:{0}", new object[] { null });
	try { 
		logger.LogWarning("This is {0}", null); 
	} 
	catch{ 
		Console.WriteLine("Only the last overload threw.");
		throw new AssertionException("Failed");
	}
}

[Test]
public void MsLoggerShouldNotThrowWhenDestructuringNullParameters()
{
    var logger = new LoggerFactory().AddConsole().CreateLogger("Test");

    logger.LogError("This is formatted for destructuring {@Destructure}", new {A=1,B=2});
    Console.WriteLine("Logs \"{ A = 1, B = 2 }\"");

    logger.LogError("This is formatted for destructuring {@Destructure}", null);
    Console.WriteLine(@"Output:
Message: System.AggregateException : 
An error occurred while writing to logger(s). (Index (zero based) must be greater than or equal to zero and less than the size of the argument list.)
----> System.FormatException : Index (zero based) must be greater than or equal to zero and less than the size of the argument list");
}
```

**Comment by chrisfcarroll** [comment] 2018-03-01 20:31
For any logger going through `Microsoft.Extensions.Logging.LoggerExtensions.LogXXX()` overloads and using `FormattedLogValues(message, args)`

**Comment by Eilon** [comment] 2018-03-01 21:01
Isn't this by design? There is an attempt to log a data value `@Destructure` but no value is provided for it.

**Comment by chrisfcarroll** [comment] 2018-03-02 12:42
Surely not? You have to be able to log some-value-that-might-be-null-you-won't-know-until-runtime ?

```
var logger = new LoggerFactory().AddConsole().CreateLogger("");
logger.LogWarning("This is {0}", 1, null);
logger.LogWarning("This is {0}", null, null);
logger.LogWarning("This is {0}", new object[] { null});
try{   logger.LogWarning("This is {0}", null); } catch{ Console.WriteLine("Only the last overload threw.")}
```
The first three overloads all happily log a null value. The last one throws.

I aver that for a logging framework, requiring the code to null check before logging is a bug not a feature?

I concede that string.Format() behaves the same, and throws on the last overload.
I concede also that my expectations were set by working with Serilog:
```
var slogger= new Serilog.LoggerConfiguration()
    .WriteTo.Console(Serilog.Events.LogEventLevel.Verbose).CreateLogger();
slogger.Warning("Serilog doesn't throw here : {0}", null);
```

**Comment by chrisfcarroll** [comment] 2018-03-02 12:47
I updated the title since I've realised that the destructuring is a red herring. The issue is when logging a single parameter of compile time type `Object` with value `null`

**Comment by Eilon** [comment] 2018-03-02 18:57
`null` has no type. I'm wondering if a different overload is being selected by the compiler based on the code being written?

**Comment by muratg** [comment] 2018-03-02 21:50
@pakrym Could you attempt a repro?

**Comment by muratg** [comment] 2018-03-02 21:52
Putting in preview2 for investigation.

**Comment by pakrym** [comment] 2018-03-05 16:26
Calling `logger.LogWarning("Log this:{0}",  null);` resolves to `(string, params object[] args)` overload where null is passed as the object array and not an item. Internally we treat null as empty array and that's why you get the original exception.

Casting null to object type forces resolution to correct overload: `logger.LogWarning("Log this:{0}",  (object)null);`

Closing: by design.

**Closed by pakrym** 2018-03-05 16:26 UTC
Labels: Investigate

**Comment by chrisfcarroll** [comment] 2018-03-05 22:58
Please, bear with me for 60 seconds.

I appreciate that that is a design for string.Format() and is visible in the API of string.Format()

But notice that in the context of the Logging classes the point you've appealed to is a hidden implementation detail?

Needing to know _the detail of underlying implementation_ in order to use an API points to it being a bug not a design.

If it were design, that detail could sensibly be surfaced in the API or documentation. 

I dare you to explain in the documentation that "a single null parameter will throw, but more than one null parameter works fine, because under the hood it uses String.Format."

?

**Comment by Eilon** [comment] 2018-03-06 07:19
@chrisfcarroll I think the issue is that in practice this shouldn't happen. Unless calling code passes in a literal `null` to the logger method, I don't think any problem happens. And if the code is passing in a literal `null`, what was it trying to do?

**Comment by chrisfcarroll** [comment] 2018-03-07 14:03
My apologies, you are quite right. 

(My code that passed a literal null was a unit test for an ILogger implementation; I accept that's my problem not an issue with your component).
