### ISSUE TITLE
Console logger output layout

### ISSUE THREAD

**Issue by moander** [aspnet/Logging#491] opened 2016-09-22 10:22 UTC
Is it possible to modify the output layout of the console logger? 

I have found that adding a Console.WriteLine() after each event makes the console output much more readable, but I have not found am easy way to implement it.

**Comment by natemcmaster** [comment] 2016-09-23 16:36
> Is it possible to modify the output layout of the console logger?

Yes, inherit from [ConsoleLogger](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Console/ConsoleLogger.cs) and add your customizations to an override of the "WriteMessage" method...

> I have not found am easy way to implement it.

...but this is also requires you replace the [ConsoleLoggerProvider](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Console/ConsoleLoggerProvider.cs) to return your custom implementation, which may not fit your definition of "easy".

**Comment by roji** [comment] 2016-09-25 13:03
+1 on this, it would be very useful for ConsoleLogger to support a configurable layout out of the box. I'm thinking about scenarios where some structured information is logged with the message and users want to output that. You currently need to use a full-fledged logging package such as NLog to achieve that, which seems a bit heavy.

I understand the desire to keep ConsoleLogger minimal and to keep it from evolving into a logging package, but this seems like a pretty basic feature with lots of value.

**Comment by Sumo-MBryant** [comment] 2016-11-02 09:29
> Yes, inherit from ConsoleLogger and add your customizations to an override of the "WriteMessage" method...

It is not possible to inherit from ConsoleLogger at present and override the "WriteMessage" method to provide similar functionality because most of the members in ConsoleLogger are private, for example:
* The lock to prevent mutual exclusion
* The functionality to manage console colours

I found it easier to simply clone the entire class unfortunately.

**Comment by hishamco** [comment] 2016-11-26 17:03
@moander can you check this PR #195

**Comment by natemcmaster** [comment] 2016-12-05 18:31
Possible duplicate of https://github.com/aspnet/Logging/issues/285

**Comment by moander** [comment] 2016-12-05 21:24
@hishamco it helps but the provider needs to resolve the ILogger type. Not sure what would be the best approach.

The [current implementation](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Console/ConsoleLoggerProvider.cs#L70) looks like this
```cs
        private ConsoleLogger CreateLoggerImplementation(string name)
        {
            return new ConsoleLogger(name, GetFilter(name, _settings), _settings.IncludeScopes);
        }
```

There is a ConsoleLoggerSettings class that is available from the AddConsole extension method. Setting a ConsoleLogger type here would make it easy to implement without having to override the provider.

**Comment by hishamco** [comment] 2016-12-05 22:12
IMHO overriding the `WriteMessage` method which is referenced here https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Console/ConsoleLogger.cs#L109 is the easiest option,

**Comment by moander** [comment] 2016-12-05 23:11
@hishamco How to get your app to use the new method?

**Comment by hishamco** [comment] 2016-12-06 00:37
You can subclass the `ConsoleLogger` to change the output as you wish

**Comment by moander** [comment] 2016-12-06 09:58
@hishamco and then what?

**Comment by hishamco** [comment] 2016-12-06 14:04
I told you before after you subclass the `ConsoleLogger` you can change the output of the log messages as you like by overriding the `WriteMessage` method

**Comment by moander** [comment] 2016-12-06 20:11
Yes, and then what?

**Comment by hishamco** [comment] 2016-12-06 20:26
> Yes, and then what?

@moander I didn't understand what you

**Comment by hishamco** [comment] 2017-01-30 07:22
@moander I come up to a scenario to extend `ConsoleLogger` but as you said before, the `WriteMessage` seems useless, because the system doesn't call the overridden method at all, which it is something strange!!

**Comment by chriscur** [comment] 2017-03-25 04:57
+1
My use case involved simply removing the new line after the event Id. To accomplish this I needed to ~~implement~~copy four classes to get the same functionality.

One suggestion may be to accept a MessageFormatDelegate with a signature matching WriteMessage in the configuration object that will let me implement my own method for formatting the line without having to implement anything custom except that one method.

**Comment by tom-thorne** [comment] 2017-07-06 10:31
+1
I too want to remove the newline.  It would be great to be able to control console output more easily than currently

**Comment by pakrym** [comment] 2018-11-06 17:02
We are not planning on adding more console logger formatting options.

**Closed by pakrym** 2018-11-06 17:02 UTC
