### ISSUE TITLE
Two custom ILoggerProvider singletons created on application startup 

### ISSUE THREAD

**Issue by Rinsen** [aspnet/Logging#701] opened 2017-09-05 21:28 UTC
I have found an issue when I add a custom ILoggerProvider in the way the example below illustrate I get two singletons instead of one.

I have made a Repo containing an example of this here, the best way to see it in action is to put a break point in the constructor for the DoNothingLogProvider.
https://github.com/Rinsen/MultipleSingletonsCreated

I have found that the second instance is created after the ILogger<Startup> instance for my Startup class is created and the first one is not Disposed before the second one is created either. 

What have I missed and why do I get this strange behavior?

```
        public static void Main(string[] args)
        {
            BuildWebHost(args).Run();
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .ConfigureLogging((hostingContext, loggingBuilder) =>
                {
                    loggingBuilder
                        .AddFilter("Microsoft", LogLevel.Warning)
                        .AddFilter("System", LogLevel.Warning)
                        .AddFilter("Problem", LogLevel.Debug)
                        .AddDoNothingLogger();
                })
                .UseStartup<Startup>()
                .Build();

        public static void AddDoNothingLogger(this ILoggingBuilder loggingBuilder)
        {
            loggingBuilder.Services.AddSingleton<ILoggerProvider, DoNothingLogProvider>();
        }
```

**Comment by moozzyk** [comment] 2017-09-06 01:25
Possibly a duplicate of https://github.com/aspnet/MetaPackages/issues/162

**Comment by Rinsen** [comment] 2017-09-06 11:34
@moozzyk
No, when I check the registered Loggers I only have one Console, one Debug and one DoNothing logger. And not two of one kind as in that issue.

**Comment by Rinsen** [comment] 2017-09-07 08:19
I have now realized that this only happens when I inject a ILogger<Startup> into my Startup class. When I don´t do that I will only get one DoNothingLogProvider.

I will try to do some more investigations with the new symbol and and source link support that we have now!

**Comment by Rinsen** [comment] 2017-09-07 09:00
The first instance is created when WebHost calls 
_startup = _hostingServiceProvider.GetRequiredService<IStartup>();
in EnsureStartup()

And the second one is created when WebHost calls
Server = _applicationServices.GetRequiredService<IServer>();
in EnsureServer()

But I unfortunately can´t get any further than this without having a deeper understanding of why these steps are running and what they do.

**Comment by cwe1ss** [comment] 2017-09-20 09:24
https://github.com/aspnet/Hosting/issues/1150

**Comment by davidfowl** [comment] 2017-09-20 09:28
Dupe of what @cwe1ss posted

**Closed by davidfowl** 2017-09-20 09:28 UTC

**Comment by Rinsen** [comment] 2017-09-20 09:37
Thanks!
